version: '3.8'
services:
  streamlit-app:
      build:
        context: .
        dockerfile: Dockerfile
      ports:
        - "8501:8501"
      depends_on:
        - ollama
      networks:
        - app-network
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    networks:
        - app-network
    volumes:
      - ollama:/root/.ollama 
networks:
  app-network:
    driver: bridge
volumes:
  ollama: